### ISSUE TITLE
More than one group levels

### ISSUE THREAD

**Issue by JanaJarecki** [cran/MicroMacroMultilevel#1]
Hi everybody,
thank you for the development of this great package. May I ask one question? How can the package handle a situation with two crossed groups (two macro levels)?

Say I have a group (houses) and another group (people) and each house has several rooms (micro-level). We want to predict the house price (macro-level) from the rating of the beauty of the rooms in a house (micro level), which was rated by m raters. This means we have two macro-level variables: One macro-at which the dependent variable sits, the house-level (`house_price` at the level of `house_id`, group 1). There is another macro-level variable grouping the individual raters (`rater`, group 2), who rated the beauty of each room of each house. This level, group 2, is NOT the level of the dependent variable.

The data then looks like this (mock data)

    house_id   house_price     rater_id         room_id        beauty
           a             2           s1              r1             1
           a             2           s1              r2             2
           a             2           s2              r1             4
           a             2           s2              r2             3
           b            10           s1              r1             1
           b            10           s1              r2             3
           b            10           s2              r1             4
           b            10           s2              r2             5

With a hierarchical linear model in lme4 I would use a formula like this
     
      house_price ~ beauty + (beauty | house_id) + (beauty | subject_id) + (1 | subject_id:house_id)

Does the micro-macro package have the capabilities to handle more than one groups (multiple macro levels)?

If not, can I extend the functions provided in the package in a sensible way?

Thank you for your help and ideas,
best
Jana Jarecki

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file.
